infrastructure/template.yaml

We are exporting function URLs but these are not needed or used so this has been removed from the `template.yaml`. This is to be consistent with the other HMRC repos.

BAU: Removed function URL outputs as they are not needed

---

.secrets.baseline
infrastructure/template.yaml

Removed `FunctionUrlConfig` as we do not use them and the account does not have permission to create it.

BAU: Removed FunctionUrlConfig

---

infrastructure/private-api.yaml
infrastructure/template.yaml
step-functions/bearer-token-retrieval.asl.json

Created a new endpoint called `/token` this fetches the bearer token from secrets manager based on `tokenType`. 
Created new state machine to fetch from secrets manager
Created OpenAPI spec
Sample request: `GET /token?tokenType=stub`
Response: `{"expiry": "1234", "token": "abc"}`
- [OJ-2356](https://govukverify.atlassian.net/browse/OJ-2356)
[OJ-2356]: https://govukverify.atlassian.net/browse/OJ-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2356: Create Private API for sharing bearer token

---

step-functions/oauth-token-generator.asl.json

The generate TOTP function was still using the function name from a preview branch. This has been updated.

BAU: Fix subsitution

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml

There seems to be a bug with `1.89.0` where `sam validate` fails even when the template is valid. Bumping to the latest version fixes this issue. 
See: https://github.com/govuk-one-login/ipv-cri-otg-hmrc/actions/runs/8393917321/job/22989943810

BAU: Update SAM version

---

deploy.sh

To allow deploying stacks locally, for use with `./deploy.sh`
Using a named role `RefreshSchedulerRole`
- [OJ-2391](https://govukverify.atlassian.net/browse/OJ-2391)
[OJ-2391]: https://govukverify.atlassian.net/browse/OJ-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2391: Update deploy.sh with CAPABILITY_NAMED_IAM

---

integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-happy.test.ts
integration-tests/tests/mocked/oauth-token-generator/sfn-constants.ts
step-functions/oauth-token-generator.asl.json

StackName not playing nice with with step function when `States.Format('${StackName}-{}', $.tokenType)`
Introduced
An extra state to get the StackName
Can re-introduce Mock Test

OJ-2391: use pass state to workaround stack interpolation

---

integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-happy.test.ts
integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-unhappy.test.ts
step-functions/oauth-token-generator.asl.json

The OAuth token generator state machine has its logic now wrapped in a parallel. This is so we can try retry exponentially on errors before failing. The reason we do it on the entire state machine is because we cannot apply it to the Lambda that calls the HMRC API due to the fact we use a TOTP code. The TOTP code has a lifespan of 30 seconds which would be expire while the retry happens.  
Screenshot:
- [OJ-2391](https://govukverify.atlassian.net/browse/OJ-2391)
[OJ-2391]: https://govukverify.atlassian.net/browse/OJ-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2391: Added exponential backoff to the state machine

---

lambdas/bearer-token-handler/src/bearer-token-handler.ts
lambdas/bearer-token-handler/tests/bearer-token-handler.test.ts

Made the expiry data half of what HMRC gives us, this is to give us a buffer when attempting to refresh.
- [OJ-2391](https://govukverify.atlassian.net/browse/OJ-2391)
[OJ-2391]: https://govukverify.atlassian.net/browse/OJ-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2391: Made expiry /2

---

infrastructure/template.yaml
lambdas/bearer-token-handler/src/bearer-token-handler.ts
lambdas/bearer-token-handler/tests/bearer-token-handler.test.ts
lambdas/secrets-manager-handler/jest.config.ts
lambdas/secrets-manager-handler/package.json
lambdas/secrets-manager-handler/src/secrets-manager-handler.ts
lambdas/secrets-manager-handler/tests/secrets-manager-handler.test.ts
lambdas/secrets-manager-handler/tsconfig.json
package-lock.json
step-functions/bearer-token-retrieval.asl.json

* Created a new Lambda that can fetch and cache secrets. 
* Secrets are cached using the AWS-Parameters-and-Secrets-Lambda-Extension layer.
* This is added to the Retrieve Bearer Token state machine as this API will have a high volume of requests coming in so for performance caching is required.  
* The cache TTL is defaulted to 5 minutes. 
* Fixed bearer-token-handler to check for "OK" status before returning and to throw on error

BAU: Add secrets caching lambda

---

.github/workflows/check-pr.yml
.github/workflows/integration-tests.yml
.github/workflows/run-aws-tests.yml
infrastructure/template.yaml
integration-tests/package.json
integration-tests/tests/aws/bearer-token-retrieval/bearer-token-retrieval.test.ts
integration-tests/tests/aws/jest.config.ts
integration-tests/tests/aws/resources/aws-helper.ts
integration-tests/tests/aws/resources/cloudformation-helper.ts
integration-tests/tests/aws/resources/stepfunction-helper.ts
integration-tests/tests/aws/setEnvVars.js

* Added infrastructure for AWS integration tests
* Added additional methods to run both express state machines and standard state machines in `stepfunction-helper.ts`
* Added happy and unhappy test for bearer token retrieval state machine
* Added GHA to run the tests
This was added to increase confidence in our code as the mocked tests do not entirely satisfy this.

OJ-2492: Integration tests

---

infrastructure/template.yaml

Removed the Lamda layer from the secrets manager handler lambda.
To use this layer in our build+ accounts we have to deploy the layer into our own accounts. This means downloading the .zip and signing it then creating it as a custom layer in the account. This is currently not being done in our govuk-one-login repos. 
After speaking to SREs/TL we have decided to leave the caching out for now as Secrets Manager supports 10,000 requests per second which will be fine for NINO/KBV. 
I have left the Lambda there so we can introduce caching in the future without having to repeat this work.

BAU: Removed Lambda layer

---

step-functions/bearer-token-retrieval.asl.json

Removed the Secrets Manager Handler Lambda call and put back the Get Secret state. This is because we are no longer using the Lambda for caching as described: https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/61

BAU: Replaced Lambda call with Get Secret

---

infrastructure/template.yaml

Imposter is not deployed to production so when trying to create the `StubOAuthUrlParameter` resource it fails as the export does not exist.

Add IsNotProdEnvironment condition to StubOAuthUrlParameter

---

infrastructure/template.yaml

NumRetries was set to 186 instead of 185. 185 is the maximum allowed value by AWS so this was failing ddeployment in staging.

Fix NumRetries for staging

---

.github/workflows/deploy-branch.yml
infrastructure/template.yaml

OJ-2465: Fix linting issues with in the SAM template
- Fix SAM linting warnings
- Fix spelling and naming errors
- Apply consistent formatting across the whole template
  - Use short forms of SAM functions where possible
  - Use double quotes where necessary
  - Use consistent spacing in brackets
  - Fix spacing and indentation issues
BAU: Address preview stack deployment issues
- Disable rollback of failed preview stacks
Resources don't need to be deleted when deployments fail, so failing and subsequent attempts can be faster since 
subsequent attempt can simply update the failed stack instead of deleting everything and starting from scratch.
This also allows to investigate failed resources since they won't be deleted every time.
- Set a stack name length limit
This is needed to ensure …

OJ-2465: Fix linting issues with in the SAM template

---

.github/workflows/delete-deployment.yml
infrastructure/template.yaml

This was missed in #70:
- Use the stack name length limit when deleting stacks for closed PRs
- Apply consistent formatting to the template

FIX: Correctly delete stacks for closed PRs

---

infrastructure/template.yaml

Created `IsProdOrIntegrationEnvironment` and `IsNotProdOrIntegrationEnvironment` conditions to prevent imposter url referencing in integration environment 
ClickOps BearerToken and TOTP parameters in OTG integration environment 
ClickOps ClientId and ClientSecret OTG integration environment
ClickOps NiNoCheckUrl in Nino Check integration environment
To configure tokenType for use with HMRC sandbox environment in hmrc-check integration account
- [OJ-2587](https://govukverify.atlassian.net/browse/OJ-2587)
[OJ-2587]: https://govukverify.atlassian.net/browse/OJ-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2587: Configure sandbox environment in OTG integration

---

infrastructure/template.yaml

Added a new alarm to the BearerTokenHandlerFunction that is triggered when the Lambda logs errors. 
The current fatal error alarms filter does not pick up error logs from the lambda and was not triggering on errors being thrown. 
- [OJ-2570](https://govukverify.atlassian.net/browse/OJ-2570)
[OJ-2570]: https://govukverify.atlassian.net/browse/OJ-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add an Error Alarm for the BearerTokenHandlerFunction

---

infrastructure/private-api.yaml
integration-tests/tests/aws/bearer-token-retrieval/bearer-token-retrieval.test.ts
package-lock.json

Added `$util.escapeJavaScript` to all the bits that in OpenAPI spec that come from user input.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
- [OJ-2610](https://govukverify.atlassian.net/browse/OJ-2610)
[OJ-2610]: https://govukverify.atlassian.net/browse/OJ-2610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2610: Escape JavaScript in VTL

---

deploy.sh
infrastructure/samconfig.toml
infrastructure/template.yaml

OJ-2567: Allow Check HMRC to invoke OTG private API
Add a list of allowed VPC endpoints to the API resource policy:
- Fetch the list of allowed VPC endpoints from the SSM param in all environment
- Additionally, in build, dev and staging allow the OTG's own VPC so that the smoke tests can invoke the API
- Join the list from the SSM with the import of the OTG's VPC endpoint using !Split and !Join functions
---
Improve deploy script
- Get stack name from the environment
- Delete the stack before deployment if it is in a failed state
- Build in the infrastructure directory
- Set the AWS region environment variable used by SAM CLI
- Synchronise samconfig.toml with the dev deployment script
Set the same flags, values and parameters as the script

OJ-2657: Restrict private API resource policy

---

infrastructure/template.yaml

Added a new alarm to the TotpGeneratorFunctionErrorAlarm that is triggered when the Lambda logs errors.
The current fatal error alarms filter does not pick up 'normal' error logs from the lambda and was not triggering on errors being thrown.
- [OJ-2617](https://govukverify.atlassian.net/browse/OJ-2617)
[OJ-2617]: https://govukverify.atlassian.net/browse/OJ-2617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2617: Add TotpGeneratorFunctionErrorAlarm 

---

infrastructure/template.yaml
lambdas/log-redaction/jest.config.ts
lambdas/log-redaction/package.json
lambdas/log-redaction/src/redact-handler.ts
lambdas/log-redaction/src/redactor.ts
lambdas/log-redaction/src/regex/secrets.ts
lambdas/log-redaction/tests/redact-handler.test.ts
lambdas/log-redaction/tests/redactor.test.ts
lambdas/log-redaction/tsconfig.json
package-lock.json
package.json

A new Lambda has been created to redact logs. This Lambda has been carried over from the existing solution in check-hmrc and it's primary purpose is to remove secrets and other sensitive information from the log groups. It then forwards the logs to a "-redacted" postfixed version of the log group. 
New logs groups postfixed with "-redacted" have been created to contain the redacted log messages and the CSLS SubscriptionFilter to Splunk has been updated to use the redacted log groups.
This has been done to stop sensitive information such as as TOTP codes and API bearer tokens being logged to Splunk.
- [OJ-2662](https://govukverify.atlassian.net/browse/OJ-2662)
[OJ-2662]: https://govukverify.atlassian.net/browse/OJ-2662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

OJ-2662: Add redaction to logs

---

.cfnlintrc
lambdas/log-redaction/src/redact-handler.ts

The redactor now sends the original message if it was not JSON.
Some messages such as errors are not JSON strings. As such, an exception `SyntaxError: Unexpected number in JSON at position ` was occurring.
Sample error: 
```
2024-08-23T09:41:35.769Z\t8465d4d8-327b-4cc4-857a-f023371aef95\tERROR\tInvoke Error \t{\"errorType\":\"Error\",\"errorMessage\":\"Error response received from HMRC 400 Bad Request\",\"stack\":[\"Error: Error response received from HMRC 400 Bad Request\",\"    at me.handler (/tmp/tmps_yb_f7o/lambdas/bearer-token-handler/src/bearer-token-handler.ts:42:13)\",\"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"]}\n to 2024-08-23T09:41:35.769Z\t8465d4d8-327b-4cc4-857a-f023371aef95\tERROR\tInvoke Error …
```

BAU: Fix redaction when message is not JSON

---

README.md
infrastructure/private-api.yaml
infrastructure/template.yaml

Files changed:
[infrastructure/private-api.yaml](https://github.com/govuk-one-login/ipv-cri-otg-hmrc/compare/IPS-1094/step-function-canaries?expand=1#diff-c98afc506962a43221fbfdc3d8330748f4ca867565692a1d497aa8cd39f72dc0)
- Edited api spec to point to live alias of state machine
[infrastructure/template.yaml](https://github.com/govuk-one-login/ipv-cri-otg-hmrc/compare/IPS-1094/step-function-canaries?expand=1#diff-1d6a0a19507d7cdddd8ff209f817d2d18f3fb22ceec6b0eb332b0a14292c69b0)
- Added `LambdaDeploymentPreference` and `StepFunctionsDeploymentPreference` parameters
- Add deployment preference to `BearerTokenRetrievalStateMachine` and `LogRedactionFunction`
- Removed references to `SecretsManagerHandlerFunction` from `BearerTokenRetrievalStateMachine`
- Added `CodeDeployServiceRole` for …

IPS-1094: Canary deployments

---

infrastructure/template.yaml

- Added `UseCanaryDeploymentAlarms` condition
- Rename alarms
Only if the if the strategy is not `AllAtOnce` should:
- Canary alarms be used to roll back deployments
- Canary alarms be deployed 
- [IPS-1155](https://govukverify.atlassian.net/browse/IPS-1155)
[IPS-1155]: https://govukverify.atlassian.net/browse/IPS-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1155: Refine alarms

---

infrastructure/template.yaml

- Set alarm actions to true
- This step should be done after the initial alarm deployment to reduce spamming the slack channels 
- [IPS-1155](https://govukverify.atlassian.net/browse/IPS-1155)
[IPS-1155]: https://govukverify.atlassian.net/browse/IPS-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1155: Set alarms to true

---

integration-tests/tests/mocked/oauth-token-generator/oauth-token-asl-types.ts
integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-unhappy.test.ts
integration-tests/tests/mocked/oauth-token-generator/sfn-container-helper.ts

Disable the parallel loop retries on the entire step function while testing retries on failing HMRC bearer token handler that uncoverable and leads to a failed state
Parallel loop retries where the reason for the test not passing as it enters an unrecoverable loop on parallel state failures on step function local. The scope of this test does not require retrying the entire step function so retries of been disabled retries on the `Refresh Token` parallel state by setting it `MaxAttempts` to zero i.e.
```
"Retry": [
{
"ErrorEquals": [
"States.ALL"
],
"BackoffRate": 2,
"MaxAttempts": 3,
"IntervalSeconds": 20
}
]
```
to
```
"Retry": [
{
"ErrorEquals": [
"States.ALL"
],
"BackoffRate": 2,
"MaxAttempts": 0,
"IntervalSeconds": 20
}
]
```
- …

OJ-2800: set refresh token retries zero

---

infrastructure/template.yaml

- Created IAM policy to deny access to:
- `OAuthTokenStateMachineLogGroup`
- State machine execution history of the `OAuthTokenStateMachine` 
- The TOTP secret is printed in both resources above, and access needs to be limited
- The process for this is for the Dev or SRE team to create the policy, and control tower to attach to the groups, see https://govukverify.atlassian.net/browse/PSREGOV-1242
- The resource policies mentioned in the above ticket already exist in this template
- [IPS-665](https://govukverify.atlassian.net/browse/IPS-665)
[IPS-665]: https://govukverify.atlassian.net/browse/IPS-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-665: Create policy for control tower

---

infrastructure/template.yaml

Deployment fails as it cannot use the ARN and must reference the role.

OJ-2887: Use role instead of function arn

---

infrastructure/template.yaml

To give our Lambda access to the TOTP Secret as the responsibility was moved away from the state machine.
- [OJ-2887](https://govukverify.atlassian.net/browse/OJ-2887)
[OJ-2887]: https://govukverify.atlassian.net/browse/OJ-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2887: Update permissions for TOTP Secret

---

infrastructure/template.yaml

The lambda resources need to depend on the corresponding log group resources to ensure that the lambda service doesn't attempt to create a duplicate log group and cause an error during deployment. Creating the dependency ensures that the log group gets created before the lambda and there is no conflict.

BAU: Fix deployment issues caused by log group conflicts

---

infrastructure/template.yaml

- Removed `DenySecretsIAMPolicy`
- No longer needed as not feasible to add to all groups/permission sets, as originally discussed
- See full thread on https://govukverify.atlassian.net/browse/PSREGOV-1242 for context
The secret and key remain inaccessible to everyone except members of the `di-ipv-cri-otg-hmrc-prod-adm-kms` group
- [IPS-665](https://govukverify.atlassian.net/browse/IPS-665)
[IPS-665]: https://govukverify.atlassian.net/browse/IPS-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-665-remove-policy

---

infrastructure/template.yaml

- Remove redaction of lambda and API log groups
- Push unredacted log groups to splunk
Because these are logs we have control over we do not need to redact them, we should just not be logging sensitive information. The redaction is only completely necessary for step functions where we can't control the log output.
This should reduce the amount of logs that are having to be processed and pushed to cloudwatch and help us avoid rate limit issues
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2897: Only redact step function logs

---

infrastructure/template.yaml
lambdas/log-redaction/package.json
lambdas/log-redaction/src/redact-handler.ts
lambdas/log-redaction/tests/redact-handler.test.ts
package-lock.json
package.json

When we create a log stream, if it already exists, the CloudWatch API will return a HTTP 400. While, for our Lambda this is OK as we ignore the error, the side effect is that Dynatrace alerts that there are errors which means our dashboard will always be red. 
To solve this, we create a new DynamoDB table that keeps track of all the log streams that we create (with a TTL of 2 hours). We use this table in our Lambda to check if we should create a new log stream not. 
We do not use the DescribeLogStream API because that has a limit of 5 executions per second which does not fit our requirements. 
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

OJ-2897: Track LogStream creations in DynamoDB and only create if not previously created

---

infrastructure/template.yaml

Renamed the TableName for RedactionLogStreamTrackingTable as it failed to create in the higher environments due to name already being used. 
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2897: Rename RedactionLogStreamTrackingTable TableName

---

infrastructure/template.yaml

Refactored BearerTokenRetrievalStateMachineAlarm to treatMissingData as notBreaching.
Refactored BearerTokenRetrievalStateMachineAlarm to make the alarm match the description.
The alarm transitions to OK every morning due to MissingData being treated as missing. The alarm triggers a slack message causing the channel to get spammed.
Also, previously the alarm did not match the description, rather than 4 failures within an hour, it was atleast 1 failure in 4 different 5 minute periods within an hour. This would mean if for example, if 100 executions failed but only within a 5 minute period it would not trigger the alarm.
https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/521
Note: See alarm threshold is ExecutionsFailed > 0 for 4 datapoints within 1 hour, to match the …

BAU: Minor refactor to BearerTokenRetrievalStateMachineAlarm

---

infrastructure/template.yaml

Allowed values for lambda deployment preference removed to allow any values.
This change was required to allow any values to be passed in the pipeline parameter. I was going to add the allowed value of LambdaCanary50Percent5Minutes as that is what is set in the pipeline but we may want to make changes in the future so this will remove the need to update this template again when pipeline parameter changes.
This will be in line with address and kbv as they dont specify allowed values.
- [IPS-1289](https://govukverify.atlassian.net/browse/IPS-1289)
[IPS-1289]: https://govukverify.atlassian.net/browse/IPS-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1289 allowed values for lambda deployment preference removed

---

infrastructure/template.yaml

- Add cloudwatch permissions for alias
- Update alarm
- Needed for the next PR, where the Subscription Filter DestinationArn is updated: https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/187/files
- [IPS-1213](https://govukverify.atlassian.net/browse/IPS-1213)
[IPS-1213]: https://govukverify.atlassian.net/browse/IPS-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1213: Add alias permissions for cloudwatch

---

infrastructure/template.yaml

- Point subscription filter of the state machine log groups to the lambda alias
- Permissions updated here: https://github.com/govuk-one-login/ipv-cri-otg-hmrc/compare/IPS-1213-perms-only?expand=1
- Follow on from initial canary PR here: https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/92
- See above
- [IPS-1213](https://govukverify.atlassian.net/browse/IPS-1213)
[IPS-1213]: https://govukverify.atlassian.net/browse/IPS-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1213: Point subscription filter to alias

---

lambdas/bearer-token-handler/src/bearer-token-handler.ts
lambdas/log-redaction/src/redact-handler.ts
lambdas/open-telemetry/jest.config.ts
lambdas/open-telemetry/package.json
lambdas/open-telemetry/src/otel-setup.ts
lambdas/open-telemetry/tsconfig.json
package-lock.json
package.json

Added open-telemetry to all the TypeScript Lambdas. This PR was influenced by https://github.com/govuk-one-login/di-id-reuse-storage/pull/1197/files
To increase our observability for performance testing.
- [OJ-3036](https://govukverify.atlassian.net/browse/OJ-3036)
[OJ-3036]: https://govukverify.atlassian.net/browse/OJ-3036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3036: Open Telemetry

---

.github/workflows/post-merge-deploy-to-dev.yml

Add `--no-cached` to sam build
We are seeing the following message when doing sam build:
```
Starting Build use cache                                                                                                                                                                                                           
Manifest file is changed (new hash: 830b1b6fb1afe0dface830fe88255fe3) or dependency folder (.aws-sam/deps/afafe926-6c25-46bf-8d2c-7d563600311e) is missing for (BearerTokenHandlerFunction), downloading dependencies and          
copying/building source                                                                                                                                                                                                            
Building codeuri: …
```

feat: add --no-cached to sam build step in package for dev

---

README.md

This is PR to test normal deployment is fine. After the [last one](https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/210) to Skip Canary
due to bad deployment in production

BAU: Test normal deployment is restored

---

.github/workflows/scan-repo.yml

Update sonar GHA to the latest commit SHA.
Upstream sonar action is being deprecated.
- [OJ-3048](https://govukverify.atlassian.net/browse/OJ-3048)
[OJ-3048]: https://govukverify.atlassian.net/browse/OJ-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3048: Update sonar action

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml
.pre-commit-config.yaml
infrastructure/template.yaml

- Upgrade node version from 18 to 22
- Remove Setup SAM step from the post merge deploy dev & build GHA.
- update pre-commit version
Node 18 has reached end of active live support and SAM CLI 1.132.0+ is needed to support node 22 runtimes.
- [OJ-3096](https://govukverify.atlassian.net/browse/OJ-3096)
[OJ-3096]: https://govukverify.atlassian.net/browse/OJ-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3096: upgrade - update node runtime version to 22

---

.github/workflows/deploy-branch.yml

Unpin sam version from preview stack. 
Reverts https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/221 but keeps the newer version of the action.
No longer requires pinning as the linting bug was fixed in Sam CLI 1.135.0 which ubuntu-latest image now uses.
- [OJ-3049](https://govukverify.atlassian.net/browse/OJ-3049)
[OJ-3049]: https://govukverify.atlassian.net/browse/OJ-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3049: Unpin sam-version from preview action

---

infrastructure/template.yaml

Add missing DeployAlarms conditions
Some alarms were being deployed when they shouldn't be and causing noise in alarms channels - eg preview stacks
Before 
After

Add missing DeployAlarms conditions

---

infrastructure/template.yaml

Role that can access secrets has been updated to `AWSReservedSSO_ApprovedAdministrator`
With the introduction of TEAM the legacy role is no longer going to be used.
- [OJ-3230](https://govukverify.atlassian.net/browse/OJ-3230)
[OJ-3230]: https://govukverify.atlassian.net/browse/OJ-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update secrets policy to use new TEAM role
