govuk-one-login/ipv-cri-otg-hmrc

.github/workflows/lint-and-test-lambdas.yml
infrastructure/template.yaml
lambdas/bearer-token-handler/.eslintignore
lambdas/bearer-token-handler/.eslintrc.js
lambdas/bearer-token-handler/jest.config.ts
lambdas/bearer-token-handler/package-lock.json
lambdas/bearer-token-handler/package.json
lambdas/bearer-token-handler/src/OAuthEvent.ts
lambdas/bearer-token-handler/src/OAuthResponse.ts
lambdas/bearer-token-handler/src/bearer-token-handler.ts
lambdas/bearer-token-handler/tests/bearer-token-handler.test.ts
lambdas/bearer-token-handler/tsconfig.json
lambdas/totp-generator/src/totp-generator-handler.ts
package-lock.json

Added a lambda to call the HMRC API to get a bearer token
- [OJ-1722](https://govukverify.atlassian.net/browse/OJ-1722)
[OJ-1722]: https://govukverify.atlassian.net/browse/OJ-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1722: Added Bearer token handler Lambda

---

infrastructure/template.yaml

`template.yaml`
There was a typo in one of the outputs and fixed missing ref which was causing deployment issues.

Fixed typo and deploy issue

---

integration-tests/tests/sfn-container-helper.ts

This change was omitted in the merged PR
The `untilExecutionCompletes` gets into an infinite loop, the changes here should prevent that by incorporate a MAX_RETRY limit
function will exit recursion in the following conditions:
Successful Execution: If the execution state becomes "ExecutionSucceeded," the function will return the history response, effectively terminating the recursion.
Retries Exhausted: If the retries parameter goes below or equal to 0, the function will throw an error with the message "Execution did not complete successfully," which will stop the recursion and propagate the error.
Catch Block Execution: If an error occurs in the catch block (other than ExecutionDoesNotExist when retries > 0), the function will continue the recursion with decreased retries.
In essence, …

BAU: add max retries to until execution completes

---

.github/workflows/lint-and-test-lambdas.yml

The github workflows
So we can manually trigger actions, there have been times were we need to run GHAs manually for testing and debugging but we can't at the moment without making a new PR

OJ-1990: Added workflow_dispatch

---

.github/workflows/pre-merge-integration-test.yml
.secrets.baseline
infrastructure/template.yaml

template.yaml
Needed default values for deployment

BAU: Added default parameter values

---

.secrets.baseline
infrastructure/template.yaml

template.yaml
Added code signing, permission boundaries and vpc config as they are needed for deployment to work.

BAU: Added permission boundaries, vpc config and code signing

---

.pre-commit-config.yaml
.secrets.baseline
CODEOWNERS
infrastructure/template.yaml

IPS-292 Added dynatrace lambda layer
Added cfn-lint and checkov to pre-commit config.
Updated Cloudformation template
Fixed all of the issues highlighted in cfn-lint.
Updated CODEOWNERS
modified:   .pre-commit-config.yaml
modified:   .secrets.baseline
modified:   CODEOWNERS
modified:   infrastructure/template.yaml
IPS-292 Added dynatrace lambda layer
Added cfn-lint and checkov to pre-commit config.
Updated Cloudformation template
Fixed all of the issues highlighted in cfn-lint.
Updated CODEOWNERS
- [IPS-292](https://govukverify.atlassian.net/browse/IPS-292)
[IPS-292]: https://govukverify.atlassian.net/browse/IPS-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-292 Added dynatrace lambda layer

---

deploy.sh
infrastructure/template.yaml
package.json

Bring in changes from the template repo.
Update the deployment script:
- Run more validation before building
- Remove unused parameter overrides
- If a stack name is not provided, construct one from the current user's AWS name
Update the template:
- Reorder sections
- Remove unused outputs
- Linting and formatting
- Move CodeSigningConfigArn to each function (it's illegal in Globals as per the documentation)

OJ-2301: Update the template and deployment script

---

integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-unhappy.test.ts

Re-instate failure test
Was commented, due to excessive timeout - the test simulates that step function running at least 3 times so we should expect it to take longer, however if the step function becomes more complex this time would increase even further. Might end up commenting this test in future but for now these changes work
- [OJ-2391](https://govukverify.atlassian.net/browse/OJ-2391)
[OJ-2391]: https://govukverify.atlassian.net/browse/OJ-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2391: re-instate failure test

---

infrastructure/private-api.yaml
infrastructure/template.yaml
step-functions/bearer-token-retrieval.asl.json

* The BearerTokenRetrievalStateMachine was out of sync with the renaming made to the OAuthTokenGeneratorStateMachine so this has been updated. 
* Added error handling to BearerTokenRetrievalStateMachine 
* Updated VTL to give fail on error
* Update the permissions for BearerTokenRetrievalStateMachine  to be able to access the bearer token secret

BAU: Fix permissions for BearerTokenRetrievalStateMachine

---

integration-tests/tests/mocked/oauth-token-generator/MockConfigFile.json
integration-tests/tests/mocked/oauth-token-generator/makefile
integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-happy.test.ts
integration-tests/tests/mocked/oauth-token-generator/oauth-token-generator-unhappy.test.ts

Make Jest test clearer, by hinting at retries

OJ-2391: Making Retries more Obvious in Jest test

---

infrastructure/template.yaml

* Added metrics to when the OTG state machine fails and succeeds.
* Added missing log group for the OAuthToken state machine

BAU: Add metrics and log group to  OAuthToken state machine

---

infrastructure/template.yaml

IPS-675 IPS-666 CSLS Subscription Filter
Added the following subscription filters:
* PrivateOTGApiAccessLogSubscriptionFilterCSLS
* BearerTokenHandlerFunctionLogsSubscriptionFilterCSLS
* TotpGeneratorFunctionLogsSubscriptionFilterCSLS
* OAuthTokenStateMachineLogsSubscriptionFilterCSLS
* BearerTokenRetrievalStateMachineLogsSubscriptionFilterCSLS
* SecretsManagerHandlerFunctionSubscriptionFilterCSLS
modified:   infrastructure/template.yaml
- [IPS-675](https://govukverify.atlassian.net/browse/IPS-675) (Task)
- [IPS-666](https://govukverify.atlassian.net/browse/IPS-666) (Epic)
[IPS-675]: https://govukverify.atlassian.net/browse/IPS-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-666]: …

IPS-675 IPS-666 CSLS Subscription Filter

---

infrastructure/template.yaml

IPS-651 IPS-623 IPS-617 HMRC OTG All Other Alarms
Added the following Alarms:
* PrivateOTGApiFatalErorMetricFilter
* PrivateOTGApiFatalErrorAlarm
* BearerTokenHandlerFunctionFatalErorMetricFilter
* BearerTokenHandlerFunctionFatalErrorAlarm
* BearerTokenHandlerFunctionThrottleAlarm
* TotpGeneratorFunctionFatalErorMetricFilter
* TotpGeneratorFunctionFatalErrorAlarm
* TotpGeneratorFunctionThrottleAlarm
* 5XXErrorAlarm
* 5XXErrorCriticalAlarm
* Token5XXApiGwErrorAlarm
* Token5XXApiGwErrorCriticalAlarm
* JsonWebKeys5XXApiGwErrorAlarm
* JsonWebKeys5XXApiGwErrorCriticalAlarm
* 4XXErrorAlarm
* Token4XXApiGwErrorAlarm
* JsonWebKeys4XXApiGwErrorAlarm
* LatencyAlarm
IPS-651 IPS-623 IPS-617 HMRC additional alarms
Added the following alarms:
* SecretsManagerHandlerFunctionFatalErorMetricFilter
* …

IPS-651 IPS-623 IPS-617 HMRC OTG All Other Alarms

---

infrastructure/template.yaml

- Don't deploy sandbox param to prod
- Don't deploy prod param to non-prod environments

OJ-2465: Deploy HMRC params to the correct accounts

---

infrastructure/template.yaml

Update the supportManualUrl from confluence to the published URL
As a DI 2nd line support engineer
I want to have the runbook for an alarm close at hand
So that I can quickly understand how to respond
- [OJ-2316](https://govukverify.atlassian.net/browse/OJ-2316)
[OJ-2316]: https://govukverify.atlassian.net/browse/OJ-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2316: Update the supportManualUrl to the published URL

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml

[IPS-820] PR Title --> Ips 820 - upload action updated to 3.9
post merge to build and post merge to dev updated with upload action version 3.9. org name and repo name had to be updated
updated to latest version
N/A
testing done in dev, see [IPS-820 ticket](https://govukverify.atlassian.net/jira/software/c/projects/IPS/boards/423?assignee=712020%3A6fb9db86-32cb-41ec-96b7-4148cd94dae4&selectedIssue=IPS-820) to view this
[IPS-820]: https://govukverify.atlassian.net/browse/IPS-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ips 820 - upload action updated to 3.9

---

infrastructure/template.yaml

`DeployAlarmsInDev` set default to `false`
To align with other projects and reduce Slack channel spam. 
- [OJ-2617](https://govukverify.atlassian.net/browse/OJ-2617)
[OJ-2617]: https://govukverify.atlassian.net/browse/OJ-2617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2617: Disable alarms in dev by default

---

infrastructure/template.yaml

Modified alarms for PagerDuty setup
- [OJ-2616](https://govukverify.atlassian.net/browse/OJ-2616)
[OJ-2616]: https://govukverify.atlassian.net/browse/OJ-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2616 - Modified alarms for PagerDuty setup

---

infrastructure/template.yaml

- Fix GetAtt
- Typo
- [IPS-665](https://govukverify.atlassian.net/browse/IPS-665)
[IPS-665]: https://govukverify.atlassian.net/browse/IPS-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix GetAtt

---

infrastructure/template.yaml

- Add secrets for monitoring in dev, build and staging
- Needed for synthetics monitoring
- [IPS-665](https://govukverify.atlassian.net/browse/IPS-665)
[IPS-665]: https://govukverify.atlassian.net/browse/IPS-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-665: Add secrets for monitoring

---

infrastructure/template.yaml

The alarm is transition from insufficientData to Ok after successful SM executions. This causes a message to slack. These changes keep the alarm meeting the description, but simplifies the implementation. It will keep the alarm in the OK state unless 4 Executions Fail within an hour.
Reduce unnecessary noise in the alerts slack channel. 

Refactor OAuth Token SM alarm to stop slack spam

---

.github/dependabot.yml
package-lock.json
package.json

- Update dependabot config to include directories and groups
- Remove esbuild-jest to fix https://github.com/govuk-one-login/ipv-cri-otg-hmrc/security/dependabot/9
- Upgrade other dependencies with high vulneabilities

Dependency upgrades for security

---

infrastructure/template.yaml
lambdas/log-redaction/src/redact-handler.ts

Small quality refactoring. 
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2897: Improvements refactoring for redaction Lambda

---

infrastructure/template.yaml

Renamed the TableName for RedactionLogStreamTrackingTable.
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2897: Rename RedactionLogStreamTrackingTable TableName

---

integration-tests/package.json
package-lock.json

Remove unsued depencency aws-testing-library
Resolve https://github.com/govuk-one-login/ipv-cri-otg-hmrc/security/dependabot/7
- [OJ-2892](https://govukverify.atlassian.net/browse/OJ-2892)
[OJ-2892]: https://govukverify.atlassian.net/browse/OJ-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2892: BAU vuln fix

---

README.md

revert to #187 [skip canary]

---

integration-tests/package.json
package-lock.json

Ran npm audit fix
Resolves;
https://github.com/govuk-one-login/ipv-cri-otg-hmrc/security/dependabot/18
https://github.com/govuk-one-login/ipv-cri-otg-hmrc/security/dependabot/17
- [OJ-3118](https://govukverify.atlassian.net/browse/OJ-3118)
[OJ-3118]: https://govukverify.atlassian.net/browse/OJ-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3118: Run audit fix

---

infrastructure/template.yaml

Change SupportManualURL to mapping
Because params can't be easily updated
Before
After
- [OJ-3214](https://govukverify.atlassian.net/browse/OJ-3214)
[OJ-3214]: https://govukverify.atlassian.net/browse/OJ-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3214: Change SupportManualURL to mapping

---

infrastructure/template.yaml

Reverts govuk-one-login/ipv-cri-otg-hmrc#256

Revert "feat: update secrets policy to use new TEAM role"

---

infrastructure/template.yaml

Hard code DT layer
So that we can easily update the version being used
- [OJ-3418](https://govukverify.atlassian.net/browse/OJ-3418)
[OJ-3418]: https://govukverify.atlassian.net/browse/OJ-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3418: Hard code DT layer to 311

---

infrastructure/template.yaml

Update DT layer to 313
Because it's the latest version
- [OJ-3418](https://govukverify.atlassian.net/browse/OJ-3418)
[OJ-3418]: https://govukverify.atlassian.net/browse/OJ-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3418: Update DT layer to 313
